project:
  type: website

website:
  title: "Bastien CHASSAGNOL personal website"
  
  navbar:
    logo: media/LOGO-GDR_BIMMM.png
    left:
 
      - href: index.qmd
        text: "Accueil"
      - href: animations.qmd  
      - href: apropos.qmd
        text: "CV"
        
format:
  html:
    theme: 
     light: flatly
     dark: darkly
    toc: true

editor: source


