---
title: 'Organisation'
lang: fr
---

## Journées ou demi-journées thématiques

Le groupe se réunit lors de journées ou demi-journées à thème (au rythme de 2 à 4 par an) avec comme ligne directrice : le **partage d'expériences sur la modélisation et l'analyse statistique de données biologiques (omiques mais pas que)**. Les journées abordent à la fois les données et les méthodes développées spécifiquement pour leur traitement pour mieux comprendre les intérêts et limites de celles-ci.

## Animation

Il est co-animé par [Julie Aubert, INRAE, UMR MIA Paris-Saclay](https://www6.inrae.fr/mia-paris/Equipes/Membres/Julie-Aubert/), [Christelle Hennequet-Antier, INRAE, MaIAGE](https://cv.archives-ouvertes.fr/christelle-hennequet-antier) et [Marie-Agnès Dillies, Institut Pasteur](https://research.pasteur.fr/fr/member/marie-agnes-dillies/).

## Vous souhaitez nous rejoindre

Vous êtes les bienvenus. N'hésitez pas à nous rejoindre et vous abonner à notre liste de diffusion pour vous tenir au courant des activités du groupe.

Pour rejoindre le gdr BiMMM et ses différents groupes de travail, c'est [ici](https://mygdr.hosted.lip6.fr/). Si votre laboratoire n'est pas encore inscrit, [contactez-nous](mailto:julie%5Bdot%5Daubert@inrae.fr) et nous ferons le nécessaire. 

Pour vous abonner à notre liste de diffusion, vous pouvez [nous contacter](mailto:julie%5Bdot%5Daubert@inrae.fr) ou envoyer un mail à `sympa@agroparistech.fr` avec comme objet `SUBSCRIBE statomique votrePrénom VotreNom`.
