---
title: 'Communications'
lang: fr
date: ''
---

#### Présentation du GT StatOmique dans le [numéro 31 des Bioinformations](https://bioinformations.fr/old/31)

#### [Poster](media/PosterA0-StatOmique-Jobim2018-V3.pdf) présenté à **JOBIM en 2018** pour décrire notre réseau.

#### [Article sur la comparaison de méthodes de normalisation pour l'analyse de données RNA-Seq](https://doi.org/10.1093/bib/bbs046)

Marie-Agnès Dillies, Andrea Rau, Julie Aubert, Christelle Hennequet-Antier, Marine Jeanmougin, Nicolas Servant, Céline Keime, Guillemette Marot, David Castel, Jordi Estelle, Gregory Guernec, Bernd Jagla, Luc Jouneau, Denis Laloë, Caroline Le Gall, Brigitte Schaëffer, Stéphane Le Crom, Mickaël Guedj, Florence Jaffrézic, on behalf of The French StatOmique Consortium, **A comprehensive evaluation of normalization methods for Illumina high-throughput RNA sequencing data analysis**, *Briefings in Bioinformatics*, Volume 14, Issue 6, November 2013, Pages 671--683, [doi.org/10.1093/bib/bbs046/](https://doi.org/10.1093/bib/bbs046)
