---
date: "2020-11-19T21:49:57-07:00"
lang: fr
title: Analyse de données transcriptomiques
categories: [webinar]
---

C. Le Priol et M.-L. Martin-Magniette nous ont présenté respectivement des méthodes d'identification de différence de variance dans des données RNA-Seq et l'outil {DiCoExpress}.

### Programme de cette première animation en mode distanciel

-   9h45 Accueil et Tour de table dans le chat

-   10h15 **Méthodes d'identification de différence de variance dans des données RNA-seq**, Christophe Le Priol

Résumé : La majorité des études sur l'expression des gènes cherchent à identifier des gènes présentant des différences de moyenne d'expression entre plusieurs populations d'échantillons. Cependant, à l'instar d'une différence de moyenne, une différence de variance d'expression de gènes peut avoir un sens biologique et physiologique. L'estimation de la variance dans les analyses classiques de différence d'expression est en général réalisée de manière approximative avant de rechercher des différences de moyenne. Deux nouvelles méthodes permettant l'identification de différences de moyenne et de variance dans des données RNA-seq dans le même cadre statistique ont récemment été publiées. Nous proposons d'évaluer les performances de ces méthodes à l'aide de données simulées. Le paramétrage permettant de détecter de manière fiable des gènes présentant une différence de variance d'expression a ainsi été déterminé avant d'appliquer ces méthodes à des jeux de données cancer.

Christophe Le Priol. [**Variance de l'expression des microARN et des ARN messagers dans le cancer.** Bio-Informatique, Biologie Systémique \[q-bio.QM\]. Université Grenoble Alpes, 2019. Français. NNT : 2019GREAS023. tel-02469341](https://tel.archives-ouvertes.fr/tel-02469341)

-   11h00 **DiCoExpress: a tool to process multifactorial RNAseq experiments from quality controls to co-expression analysis through differential analysis based on contrasts inside GLM models**, [Marie-Laure Martin-Magniette](https://www6.inrae.fr/mia-paris/Equipes/Membres/Marie-Laure-Martin-Magniette)

Lambert, I., Paysant-Le Roux, C., Colella, S. et al. **DiCoExpress: a tool to process multifactorial RNAseq experiments from quality controls to co-expression analysis through differential analysis based on contrasts inside GLM models.** *Plant Methods* 16, 68 (2020). <https://doi.org/10.1186/s13007-020-00611-7>

-   11h30 Discussion sur le fonctionnement de StatOmique et les événements à venir
